### ISSUE TITLE
demo引入的vue组件似乎不支持script标签内容

### ISSUE THREAD

**Issue by tujindong** [hairyf/markdown-it-vitepress-demo#8]
script标签内编写内容会被解析错误
![image](https://github.com/hairyf/markdown-it-vitepress-demo/assets/22135295/a024e0ae-8df5-4adf-820b-0033cbc09618)

**Comment by tujindong** [comment]
script标签中写入以下内容会被解析错误： 
`<script lang="ts" setup>
import { Search, Edit } from '@element-plus/icons-vue';
</script>
`

**Comment by hairyf** [comment]
嗨，你需要换行处理，由于 import 会被特殊处理，import 需要换行

**Comment by hairyf** [comment]
![image](https://github.com/hairyf/markdown-it-vitepress-demo/assets/49724027/856cdabb-31f2-4b5c-a88e-9c5e9e04dab5)

**Comment by hairyf** [comment]
能提供更多信息吗？

**Comment by tujindong** [comment]
复现步骤：
1.在vitepress 引入 `markdown-it-vitepress-demo^0.1.8` 插件。
![image](https://github.com/hairyf/markdown-it-vitepress-demo/assets/22135295/7bce630b-01e3-4672-ac4d-9899b194730c)
2.md文件引入外部vue文件。
![image](https://github.com/hairyf/markdown-it-vitepress-demo/assets/22135295/90b89496-83d6-45b8-b33d-b1063ee7af82)
3.vue文件script标签编写如下代码片段。
`<script lang="ts" setup>
import {
  Check,
  Delete,
  Edit,
  Message,
  Search,
  Star
} from '@element-plus/icons-vue';
</script>
<template></template>`
![image](https://github.com/hairyf/markdown-it-vitepress-demo/assets/22135295/83d84113-32dc-4d6b-a386-9048bdbc06cc)
4.页面报解析错误。
![image](https://github.com/hairyf/markdown-it-vitepress-demo/assets/22135295/3ae9210d-8605-4860-adfd-e494c5d0d5f6)
5.该场景多次测试为引入Icons组件较多时会出现（大于5个）

**Comment by hairyf** [comment]
在 esbuild 处理前，会将所有的 import 作为标记，防止 esbuild 删除代码，换行会导致异常，我会想办法解决它

**Comment by hairyf** [comment]
如果你的项目没有使用 typescript，请把 lang="ts" 关闭，这将阻止 ts 编译，防止这个错误发生

**Comment by hairyf** [comment]
0.1.11 已修复
